/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Blook { 'cost' : bigint, 'name' : string, 'rarity' : string }
export interface Question {
  'id' : bigint,
  'correctIndex' : bigint,
  'prompt' : string,
  'choices' : Array<string>,
}
export interface QuestionSet {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'questions' : Array<Question>,
  'isPublic' : boolean,
}
export interface User {
  'id' : bigint,
  'xp' : bigint,
  'name' : string,
  'coins' : bigint,
}
export interface UserProfile {
  'xp' : bigint,
  'name' : string,
  'equippedBlook' : [] | [string],
  'coins' : bigint,
  'ownedBlooks' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addShopBlook' : ActorMethod<[string, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'buyBlook' : ActorMethod<[string], undefined>,
  'createUser' : ActorMethod<[string], undefined>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<User>>,
  'getQuestionSet' : ActorMethod<[bigint], [] | [QuestionSet]>,
  'getShopBlooks' : ActorMethod<[], Array<[string, Blook]>>,
  'getUser' : ActorMethod<[], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'giveCoins' : ActorMethod<[Principal, bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchQuestionSets' : ActorMethod<[string], Array<QuestionSet>>,
  'submitQuestionSet' : ActorMethod<[string, Array<Question>], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];