/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'xp' : IDL.Nat,
  'name' : IDL.Text,
  'coins' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'name' : IDL.Text,
  'equippedBlook' : IDL.Opt(IDL.Text),
  'coins' : IDL.Nat,
  'ownedBlooks' : IDL.Vec(IDL.Text),
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'correctIndex' : IDL.Nat,
  'prompt' : IDL.Text,
  'choices' : IDL.Vec(IDL.Text),
});
export const QuestionSet = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'questions' : IDL.Vec(Question),
  'isPublic' : IDL.Bool,
});
export const Blook = IDL.Record({
  'cost' : IDL.Nat,
  'name' : IDL.Text,
  'rarity' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addShopBlook' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'buyBlook' : IDL.Func([IDL.Text], [], []),
  'createUser' : IDL.Func([IDL.Text], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getQuestionSet' : IDL.Func([IDL.Nat], [IDL.Opt(QuestionSet)], ['query']),
  'getShopBlooks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Blook))],
      ['query'],
    ),
  'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'giveCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchQuestionSets' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuestionSet)],
      ['query'],
    ),
  'submitQuestionSet' : IDL.Func([IDL.Text, IDL.Vec(Question)], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'xp' : IDL.Nat,
    'name' : IDL.Text,
    'coins' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'name' : IDL.Text,
    'equippedBlook' : IDL.Opt(IDL.Text),
    'coins' : IDL.Nat,
    'ownedBlooks' : IDL.Vec(IDL.Text),
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'correctIndex' : IDL.Nat,
    'prompt' : IDL.Text,
    'choices' : IDL.Vec(IDL.Text),
  });
  const QuestionSet = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'questions' : IDL.Vec(Question),
    'isPublic' : IDL.Bool,
  });
  const Blook = IDL.Record({
    'cost' : IDL.Nat,
    'name' : IDL.Text,
    'rarity' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addShopBlook' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'buyBlook' : IDL.Func([IDL.Text], [], []),
    'createUser' : IDL.Func([IDL.Text], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getQuestionSet' : IDL.Func([IDL.Nat], [IDL.Opt(QuestionSet)], ['query']),
    'getShopBlooks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Blook))],
        ['query'],
      ),
    'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'giveCoins' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchQuestionSets' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuestionSet)],
        ['query'],
      ),
    'submitQuestionSet' : IDL.Func(
        [IDL.Text, IDL.Vec(Question)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };